// Mocks generated by Mockito 5.4.6 from annotations
// in yutori_kyoshitu/test/features/ai_assistant/presentation/widgets/ai_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:yutori_kyoshitu/core/services/api_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i4.Future<Map<String, dynamic>> callAIAssist({
    required String? action,
    required String? selectedText,
    required String? instruction,
    required Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #callAIAssist,
          [],
          {
            #action: action,
            #selectedText: selectedText,
            #instruction: instruction,
            #context: context,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> transcribeAudio(String? audioPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #transcribeAudio,
          [audioPath],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> generateConstrainedHTML({
    required String? prompt,
    String? customInstruction = '',
    String? seasonTheme = '',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateConstrainedHTML,
          [],
          {
            #prompt: prompt,
            #customInstruction: customInstruction,
            #seasonTheme: seasonTheme,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}
