name: gakkoudayori_ai
description: 学校だよりAI - 音声入力システム
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # API呼び出し（STT・Gemini）
  http: ^1.1.0
  
  # Web Audio API, JavaScript Bridge
  web: ^0.5.1
  
  # HTML Widget for rendering HTML content
  flutter_widget_from_html: ^0.15.0
  flutter_widget_from_html_core: ^0.15.0
  google_fonts: ^6.2.1
  
  # 画像アップロード・処理
  file_picker: ^6.1.1           # マルチプラットフォーム・複数選択対応（quill_html_editor互換）
  image_picker: ^1.0.7           # カメラ・ギャラリー（モバイル）
  desktop_drop: ^0.4.4           # ドラッグ&ドロップ（デスクトップ）
  image: ^4.1.7                  # 基本的な画像処理・リサイズ
  flutter_image_compress: ^2.2.0 # 高度な圧縮・最適化
  cached_network_image: ^3.3.1   # ネットワーク画像キャッシュ
  
  # リッチテキストエディタ
  flutter_quill: ^8.5.0          # Flutter用Quillエディタ（extensions互換）
  flutter_quill_extensions: ^0.6.7 # 画像・リンク等拡張
  quill_html_editor: ^2.2.8      # HTML変換・Web最適化
  
  # PDF生成・印刷プレビュー
  printing: ^5.12.0              # 印刷プレビュー・PDF出力
  pdf: ^3.10.7                   # PDF文書作成・カスタマイズ
  universal_html: ^2.2.4         # HTML解析（Web）
  
  # Google Classroom連携
  googleapis: ^13.1.0            # Google APIs クライアント
  googleapis_auth: ^1.6.0        # OAuth認証
  google_sign_in: ^6.2.1         # Googleサインイン
  firebase_core: ^2.32.0         # Firebase Core
  firebase_auth: ^4.19.5         # Firebase認証と統合
  firebase_storage: ^11.7.4      # Cloud Storage
  
  # レスポンシブデザイン
  flutter_layout_grid: ^2.0.7    # CSS Gridライクなレイアウト
  responsive_framework: ^1.4.0    # レスポンシブヘルパー
  
  # 状態管理
  provider: ^6.1.2               # 軽量・Flutterチーム公式
  
  # プログレス・インジケーター
  percent_indicator: ^4.2.3      # アップロード進捗
  
  # その他UI強化
  shimmer: ^3.0.0               # ローディングプレースホルダー
  flutter_staggered_grid_view: ^0.7.0 # 画像グリッド表示
  modal_bottom_sheet: ^3.0.0     # モーダル表示

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # コード品質
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/audio/    # 音声関連ファイル用
    - assets/images/
    - assets/icons/
    - assets/data/     # データファイル用

