name: gakkoudayori_ai
description: 学校だよりAI - 音声入力システム
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 状態管理
  provider: ^6.1.2
  
  # ルーティング
  go_router: ^14.2.0
  
  # API呼び出し（STT・Gemini）
  http: ^1.1.0
  
  # WebSocket通信
  web_socket_channel: ^3.0.0
  
  # Web Audio API, JavaScript Bridge
  web: ^1.1.0
  
  # HTML Widget for rendering HTML content
  flutter_widget_from_html: ^0.15.0
  flutter_widget_from_html_core: ^0.15.0
  
  # 画像アップロード・処理
  file_picker: ^8.0.0+1
  image_picker: ^1.0.7
  image: ^4.1.7
  flutter_image_compress: ^2.2.0
  
  # ドラッグ&ドロップ (Web)
  flutter_dropzone: ^4.0.1
  
  # Firebase (Cloud Storage用)
  firebase_core: ^3.14.0
  firebase_storage: ^12.4.7
  firebase_auth: ^5.6.0
  
  # フォント・デザイン
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # コード品質
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/audio/    # 音声関連ファイル用
    - assets/images/
    - assets/icons/

