repos:
  # Python品質管理
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        files: ^backend/
        
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^backend/
        
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        files: ^backend/
        args: [--fix, --exit-non-zero-on-fix]
        
  # ADK互換性テスト
  - repo: local
    hooks:
      - id: adk-compatibility-test
        name: ADK v1.0.0 互換性テスト
        entry: bash -c 'cd backend && poetry run python test_adk_compatibility.py'
        language: system
        files: ^backend/agents/.*\.py$
        pass_filenames: false
        
  # 一般的な品質管理
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: .*\.md$
      - id: end-of-file-fixer
        exclude: .*\.md$
      - id: check-yaml
        exclude: ^frontend/
      - id: check-json
        exclude: ^frontend/
      - id: check-merge-conflict
      - id: check-case-conflict 