// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAROJC6oomnN4tl1Sv27fcE5yaB_vIzXxc',
    appId: '1:309920383305:web:fa0ae9890d4e7bf2355a98',
    messagingSenderId: '309920383305',
    projectId: 'yutori-kyoshitu',
    authDomain: 'yutori-kyoshitu.firebaseapp.com',
    storageBucket: 'yutori-kyoshitu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhVBhm6_QZ8YXXkJyYvJ8oWx4dY7WZz9c',
    appId: '1:123456789012:android:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'yutori-kyoshitu',
    storageBucket: 'yutori-kyoshitu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhVBhm6_QZ8YXXkJyYvJ8oWx4dY7WZz9c',
    appId: '1:123456789012:ios:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'yutori-kyoshitu',
    storageBucket: 'yutori-kyoshitu.appspot.com',
    iosBundleId: 'com.yutori.kyoshitsu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhVBhm6_QZ8YXXkJyYvJ8oWx4dY7WZz9c',
    appId: '1:123456789012:macos:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'yutori-kyoshitu',
    storageBucket: 'yutori-kyoshitu.appspot.com',
    iosBundleId: 'com.yutori.kyoshitsu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhVBhm6_QZ8YXXkJyYvJ8oWx4dY7WZz9c',
    appId: '1:123456789012:web:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'yutori-kyoshitu',
    authDomain: 'yutori-kyoshitu.firebaseapp.com',
    storageBucket: 'yutori-kyoshitu.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );
} 